- name: Download Kits
  hosts: localhost
  vars:
    kit_folder: /home/core/kits
    rke_version: v1.0.4
    rancher_cli_version: v2.3.2

  tasks:

  - set_fact:
      env: {}
    when: proxy is not defined

  - set_fact:
      env: 
        http_proxy: "{{ proxy.http }}"
        https_proxy: "{{ proxy.http }}"
        no_proxy: "{{ proxy.except }}"
    when: proxy is defined

  - name: Create kits folder
    file:
      path: "{{ kit_folder }}/{{ inventory_hostname }}"
      state: directory
    delegate_to: localhost

  - name: Download files
    get_url:
      url: "{{ item.url }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
    with_items:
    - url:   https://github.com/rancher/rke/releases/download/{{ rke_version }}/rke_linux-amd64
      dest: "{{ kit_folder }}/rke"
      mode: 755
    - url:  https://github.com/rancher/cli/releases/download/{{ rancher_cli_version }}/rancher-linux-amd64-{{ rancher_cli_version }}.tar.gz
      dest: "{{ kit_folder }}/rancher.tar.gz"
      mode: 644
    - url:  https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.ova
      dest: "{{ kit_folder }}/ubuntu1804.ova"
      mode: 644
    environment: "{{ env }}"

  - name: Extract rancher cli
    unarchive:
      src: "{{ kit_folder }}/rancher.tar.gz"
      dest: "{{ kit_folder }}"
      remote_src: yes

  - name: Copy rancher cli tool to expected location
    copy:
      src: "{{ kit_folder }}/rancher-{{ rancher_cli_version }}/rancher"
      dest: "{{ kit_folder }}/"
