- set_fact:
    user_cluster_id: c-zqhp7
    user_pool_master_prefix: user-mas
    user_pool_worker_prefix: user-wrk


- name: Create Node Pool
  uri:
    url: "{{ rancher.url }}/{{ rancher.apiversion }}/NodePools"
    validate_certs: "{{ rancher.validate_certs }}"
    headers:
      Accept: application/json
      Content-Type: application/json
      Authorization: Bearer {{ rancher.bearer_token }}
    method: POST
    timeout: 4
    status_code:
    - 201
    body_format: json
    body:
      clusterId: "{{ user_cluster_id }}"
      controlPlane: false
      etcd: false
      deleteNotReadyAfterSecs: 0
      displayName: "Pool"
      hostnamePrefix: "{{ user_pool_worker_prefix }}"
      name: "worker-pool"
      namespaceId: ""
      nodeTaints: []
      nodeTemplateId: "{{ node_template_id }}"
      quantity: 1
      worker: true
  delegate_to: localhost
  register: res

- debug: var=res
