- set_fact:
    user_pool_master_prefix: clh-user-mas
    user_pool_worker_prefix: clh-user-wrk

- name: Create master Pool
  uri:
    url: "{{ rancher.url }}/{{ rancher.apiversion }}/NodePools"
    validate_certs: "{{ rancher.validate_certs }}"
    headers:
      Accept: application/json
      Content-Type: application/json
      Authorization: Bearer {{ rancher.bearer_token }}
    method: POST
    timeout: 4
    status_code:
    - 201
    body_format: json
    body:
      clusterId: "{{ clusters.json.data[0].id }}"
      etcd: true
      controlPlane: true
      worker: false
      deleteNotReadyAfterSecs: 0
      displayName: "Pool"
      hostnamePrefix: "{{ user_pool_worker_prefix }}"
      name: "worker-pool"
      namespaceId: ""
      nodeTaints: []
      nodeTemplateId: "{{ node_templates.json.data[0].id }}"
      quantity: 1
  delegate_to: localhost
  register: res

- name: Create worker Pool
  uri:
    url: "{{ rancher.url }}/{{ rancher.apiversion }}/NodePools"
    validate_certs: "{{ rancher.validate_certs }}"
    headers:
      Accept: application/json
      Content-Type: application/json
      Authorization: Bearer {{ rancher.bearer_token }}
    method: POST
    timeout: 4
    status_code:
    - 201
    body_format: json
    body:
      clusterId: "{{ clusters.json.data[0].id }}"
      etcd: false
      controlPlane: false
      worker: true
      deleteNotReadyAfterSecs: 0
      displayName: "Pool"
      hostnamePrefix: "{{ user_pool_worker_prefix }}"
      name: "worker-pool"
      namespaceId: ""
      nodeTaints: []
      nodeTemplateId: "{{ node_templates.json.data[0].id }}"
      quantity: 1
  delegate_to: localhost
  register: res

- debug: var=res
