- name: Configure Proxy
  include_tasks: proxy_{{ ansible_distribution }}.yml

- name: Update Package Manager
  become: true
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install Pkgs 
  become: true
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - firewalld


- name: Enable firewall
  become: true
  systemd:
    name: firewalld
    enabled: yes
    state: started

# see https://rancher.com/docs/rancher/v2.x/en/installation/options/firewall/
- name: Configure required ports in public zone
  become: true
  firewalld:
    zone: public
    port: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  with_items:
   - 80/tcp     # http traffic
   - 443/tcp    # https traffic
   - 2376/tcp   # Docker Daemon TLS port
   - 2379/tcp
   - 2380/tcp
   - 4001/tcp
   - 6443/tcp   # kubernetes API server
   - 8472/udp
   - 9099/tcp
   - 10250/tcp
   - 10254/tcp
   - 30000-32767/tcp
   - 30000-32767/udp

- name: Add frontend interface to public zone
  become: true
  firewalld:
    zone: public
    interface: ens192
    permanent: yes
    immediate: yes
    state: enabled

- name: Install Docker
  become: true
  shell: |
    export HTTP_PROXY={{ proxy.http }}
    export HTTPS_PROXY={{ proxy.http }}
    export NO_PROXY={{ proxy.except }}
    curl https://releases.rancher.com/install-docker/19.03.sh | sh

- name: Add user to Docker group
  shell: whoami
  register: whoami

- name: Add user to Docker group
  become: true
  user:
    name: "{{ whoami.stdout }}"
    groups: docker

