#- name: Configure Proxy
#  become: true
#  template:
#    src: proxy.conf.j2
#    dest: /etc/apt/apt.conf.d/proxy.conf
#  when: proxy is defined

- name: Create Docker service directory
  become: true
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Add proxy details
  become: true
  template: 
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  when: proxy is defined
  notify: Restart Docker
