###
# Copyright (2020) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

---
kubeconfig_file:  "{{ install_dir }}/kube_config_rancher-cluster.yml"
certmanager_crds:  'https://raw.githubusercontent.com/jetstack/cert-manager/release-0.12/deploy/manifests/00-crds.yaml'  # update getkits then point to the staging area (tbd)
cert_manager_deploy_timeout: 300  # timeout in seconds. 5mns should be more than enough
rancherserver_deploy_timeout: 600 # timeout in seconds. 10mns should be more than enough
rancherserver_hostname: "{{ rancher.hostname }}"
rancherserver_tls_source: "{{ rancher.tls_source | default('rancher') | lower }}"
rancherserver_tls_privateCA: "{{ rancher.tls_privateCA | default('false') }}"
rancherserver_tls_cacert_file: "{{ rancher.tls_cacert_file | default('null') }}"
rancherserver_tls_certchain_file: "{{ rancher.tls_certchain_file | default('null') }}"
rancherserver_tls_certkey_file: "{{ rancher.tls_certkey_file | default('null') }}"
