###
# Copyright (2020) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
### 
---
- name: Create VM
  delegate_to: localhost
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    esxi_hostname: "{{ esxi_host }}"
    datacenter: "{{ datacenter }}"
    datastore: "{{ datastore }}"
    folder: "{{ datacenter }}/vm/{{ folder }}"
    name: "{{ inventory_hostname }}"
    template: "{{ template }}"
    state: present
    customvalues: "{{ customvalues }}"
    hardware:
      memory_mb: "{{ ram }}"
      memory_reservation: "{{ ram }}"
      num_cpus: "{{ cpus }}"
    networks: "{{ networks }}"
    disk:
      "{{ disks_specs }}"
  register: res

- name: Find the name of the folder containing the VM files
  set_fact:
    fname: "{{ fpath.split(' ')[1] }}"
  vars:
    fpath: "{{ res.instance.hw_files[0].split('/')[0] }}"

- name: Copy iso image to datastore if VM is Powered Off
  vsphere_copy:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    src: "{{ cloudinit_folder }}/{{ inventory_hostname }}/{{ inventory_hostname }}.iso"
    datacenter: "{{ datacenter }}"
    datastore: "{{ datastore }}"
    path: "{{ fname }}/cloud-init.iso"
    validate_certs: "{{ vcenter_validate_certs }}"
  delegate_to: localhost
  when: res.instance.hw_power_status == "poweredOff"

- name: Attach the cloud-init CDROM
  delegate_to: localhost
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ datacenter }}"
    cdrom: 
      state: present
      type: iso
      iso_path: "[{{ datastore }}] {{ fname }}/cloud-init.iso"
    name: "{{ inventory_hostname }}"
    disk:
      "{{ disks_specs }}"
    state: present
  when: res.instance.hw_power_status == "poweredOff"
