###
# Copyright (2020) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
### 
---
- name: Get CSI Datastore Info
  vmware_datastore_info:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter_name: '{{ datacenter }}'
    name: "{{ csi_datastore_name | default(datastores[0]) }}"
    validate_certs:  "{{ vcenter_validate_certs }}"
  delegate_to: localhost
  register: csi_datastore_info

- name: Create CSI Secret
  k8s:
    state: present
    definition:
      kind: Secret
      apiVersion: v1
      data:
        csi-vsphere.conf: "{{ lookup('template', 'csi-secret.conf.j2') | b64encode }}"
      metadata:
        name: vsphere-config-secret
        namespace: kube-system

- name: Create CSI Config Map
  k8s:
    state: present
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: cloud-config
        namespace: kube-system
      data:
        vsphere.conf: "{{ lookup('template', 'csi-vsphere.conf.j2') }}"

- name: Create Cloud Controller Manager Roles
  k8s:
    state: present
    definition: "{{ lookup('file','cloud-controller-manager-roles.yaml') }}"

- name: Create Cloud Controller Manager Role Bindings
  k8s:
    state: present
    definition: "{{ lookup('file','cloud-controller-manager-role-bindings.yaml') }}"

- name: Create Cloud Controller Manager Daemon Set
  k8s:
    state: present
    definition: "{{ lookup('file','cloud-controller-manager-ds.rancher.yaml') }}"

- name: Create Controller RBAC
  k8s:
    state: present
    definition: "{{ lookup('file','vsphere-csi-controller-rbac.yaml') }}"
  when: csi_driver == "vsphere"

- name: Create Controller StatefulSet and Driver
  k8s:
    state: present
    definition: "{{ lookup('file','vsphere-csi-controller-ss.yaml') }}"
  when: csi_driver == "vsphere"

- name: Create CSI DaemonSet
  k8s:
    state: present
    definition: "{{ lookup('file','vsphere-csi-node-ds.yaml') }}"
  when: csi_driver == "vsphere"

- name: See if the CSI Storage Class exists
  k8s_info:
    kind: StorageClass
    name: "{{ csi_storageclass_name }}"
  register: sc

- debug:
    msg: "Storage Class '{{ csi_storageclass_name }}' already exists."
  when: sc.resources | count > 0

- name: Create CSI Storage Class
  k8s:
    state: present
    definition: "{{ lookup('template','csi-sc.yml.j2') }}"
  when: sc.resources | count < 1
